import type { Package, PortfolioItem, Reel } from "@/lib/supabase/types";

// Used when Supabase has no data yet (first deploy / preview without env vars).
// Mirrors the 2026 lineup in supabase/migrations/003_packages_2026_lineup.sql.

export const fallbackMarketingPackages: Package[] = [
  {
    id: "fallback-m1",
    section: "marketing",
    name: "STARTER SPARK — เพจสตาร์ทแบบมืออาชีพ",
    name_en: "Starter Spark — SME Page Kickstart",
    subtitle: null,
    price: 9900,
    features: [
      "คอนเทนต์ 8 โพสต์/เดือน (กราฟิก + แคปชั่น 2 ภาษา TH/EN)",
      "Reels / TikTok / Shorts vertical video 2 คลิป/เดือน",
      "Content Plan รายเดือน + Hashtag/AIEO research",
      "ตั้งค่า Google Business Profile + AIEO meta (ครั้งเดียว)",
      "LINE OA broadcast template 2 ชุด/เดือน",
      "รายงานผล + insight ทุก 30 วัน",
      "ทีม chat support จันทร์-ศุกร์",
    ],
    features_en: [
      "8 social posts/month (graphic + bilingual caption)",
      "2 vertical Reels/TikTok/Shorts per month",
      "Monthly content plan + Hashtag/AIEO research",
      "Google Business Profile + AIEO meta setup (one-time)",
      "2 LINE OA broadcast templates per month",
      "Monthly performance report + insight",
      "Chat support Mon–Fri",
    ],
    channels: ["Facebook, IG, TikTok, LINE OA"],
    channels_en: ["Facebook, IG, TikTok, LINE OA"],
    best_fit: "SME ใหม่ — ร้านอาหาร คาเฟ่ ร้านเสริมสวย ที่ต้องการเพจดูเป็นมืออาชีพ",
    best_fit_en:
      "New SMEs — restaurants, cafés, and salons that want a polished page",
    is_recommended: false,
    sort_order: 1,
    is_active: true,
  },
  {
    id: "fallback-m2",
    section: "marketing",
    name: "GROWTH ENGINE — เร่งเครื่องโซเชียลครบช่อง",
    name_en: "Growth Engine — Multi-Channel Content + Ads",
    subtitle: null,
    price: 24900,
    features: [
      "คอนเทนต์ 14 โพสต์/เดือน ครอบคลุม FB / IG / TikTok / LINE",
      "Reels / TikTok vertical video 5 คลิป/เดือน (in-house shoot 1 วัน)",
      "ถ่ายภาพ product / lifestyle 15 ภาพ/เดือน",
      "Ads management (FB + TikTok) — ไม่ markup ค่า media",
      "LINE OA broadcast 4 ครั้ง + Rich menu refresh",
      "AI Content Engine — template + prompt library ของ Deduck",
      "AIEO + SEO monthly tune-up",
      "Monthly dashboard + strategy call 30 นาที",
    ],
    features_en: [
      "14 posts/month across FB / IG / TikTok / LINE",
      "5 Reels / TikTok vertical videos (1 in-house shoot day included)",
      "15 product / lifestyle photos per month",
      "Ads management on FB + TikTok (media cost unmarked)",
      "4 LINE OA broadcasts + Rich Menu refresh",
      "AI Content Engine — Deduck-built template + prompt library",
      "Monthly AIEO + SEO tune-up",
      "Monthly dashboard + 30-min strategy call",
    ],
    channels: ["Facebook, IG, TikTok, LINE OA, Ads, AIEO"],
    channels_en: ["Facebook, IG, TikTok, LINE OA, Ads, AIEO"],
    best_fit:
      "SME ที่ยอดขายเดินแล้ว ต้องการ scale 2-3 ช่อง + ยิง Ads จริงจัง (F&B chain, beauty, e-commerce ระดับเริ่มต้น)",
    best_fit_en:
      "Established SMEs ready to scale across 2-3 channels + serious paid ads (F&B chains, beauty, early-stage e-commerce)",
    is_recommended: true,
    sort_order: 2,
    is_active: true,
  },
  {
    id: "fallback-m3",
    section: "marketing",
    name: "BRAND PRO — เอเจนซี่แบบครบทีม",
    name_en: "Brand Pro — Full-Stack Marketing Team",
    subtitle: null,
    price: 49900,
    features: [
      "คอนเทนต์ 20+ โพสต์/เดือน ครบทุก primary channel",
      "Reels / TikTok / Shorts 10 คลิป + Long-form 1 ชิ้น (2-3 นาที)",
      "ถ่าย on-location 2 วัน/เดือน (รวม drone เมื่อเหมาะ)",
      "TikTok Shop / Live Commerce setup + 2 live session/เดือน",
      "Micro-Influencer activation 2 คน/เดือน (5k–50k followers)",
      "LINE OA automation flow + broadcast 6 ครั้ง",
      "AIEO + SEO + Google Business + Local SEO tune",
      "Bi-weekly strategy call + performance dashboard",
    ],
    features_en: [
      "20+ posts/month across every primary channel",
      "10 Reels / TikTok / Shorts + 1 long-form video (2-3 min)",
      "2 on-location shoot days/month (incl. drone when fitting)",
      "TikTok Shop / Live Commerce setup + 2 live sessions/month",
      "2 Micro-Influencer activations/month (5k–50k followers)",
      "LINE OA automation flow + 6 broadcasts",
      "AIEO + SEO + Google Business + Local SEO tune-up",
      "Bi-weekly strategy call + performance dashboard",
    ],
    channels: [
      "Facebook, IG, TikTok Shop, LINE OA, Google Business, Influencer",
    ],
    channels_en: [
      "Facebook, IG, TikTok Shop, LINE OA, Google Business, Influencer",
    ],
    best_fit:
      "SME ขนาดกลาง — Real Estate developer, F&B group, beauty brand ที่ต้องการทีมการตลาดข้างนอกแทน in-house",
    best_fit_en:
      "Mid-size SMEs — real estate developers, F&B groups, beauty brands that need an outsourced marketing team",
    is_recommended: false,
    sort_order: 3,
    is_active: true,
  },
  {
    id: "fallback-m4",
    section: "marketing",
    name: "BRAND POWERHOUSE — ผู้นำในหมวด",
    name_en: "Brand Powerhouse — Category Leader Retainer",
    subtitle: null,
    price: 89900,
    features: [
      "เนื้อหา 30+ ชิ้น/เดือน ทุก format ทุก channel",
      "Production shoot 4 วัน/เดือน (drone + studio + on-location)",
      "Long-form video 2 ชิ้น/เดือน (3-5 นาที) + cutdown 8-12 คลิป",
      "TikTok Shop full ops — script + 4 live sessions + creator network 4-5 คน",
      "LINE OA CRM ครบ funnel (acquisition → retention → win-back)",
      "Mid-tier Influencer 1 คน + Micro 3 คน/เดือน",
      "Brand strategy + quarterly campaign concept",
      "Dedicated Account Director + weekly call",
      "AIEO + SEO + Local + Google Ads setup",
    ],
    features_en: [
      "30+ pieces/month across every format and channel",
      "4 production shoot days/month (drone + studio + on-location)",
      "2 long-form videos/month (3-5 min) + 8-12 cutdown clips",
      "TikTok Shop full ops — script + 4 live sessions + 4-5 creators",
      "Full-funnel LINE OA CRM (acquisition → retention → win-back)",
      "1 mid-tier influencer + 3 micro creators activated monthly",
      "Brand strategy + quarterly campaign concept",
      "Dedicated Account Director + weekly call",
      "AIEO + SEO + Local + Google Ads setup",
    ],
    channels: ["ครบทุก channel + Influencer network + Google Ads + LINE CRM"],
    channels_en: [
      "Every major channel + Influencer network + Google Ads + LINE CRM",
    ],
    best_fit:
      "Brand ระดับภูมิภาค / chain หลายสาขา / property project / luxury hotel ที่ต้องการ marketing partner ระยะยาว",
    best_fit_en:
      "Regional brands / multi-location chains / property projects / luxury hotels that need a long-term marketing partner",
    is_recommended: false,
    sort_order: 4,
    is_active: true,
  },
];

export const fallbackProductionPackages: Package[] = [
  {
    id: "fallback-p1",
    section: "production",
    name: "CONTENT BURST — ชุดวิดีโอเร่งด่วน",
    name_en: "Content Burst — Vertical Video Pack",
    subtitle: null,
    price: 19900,
    features: [
      "1 วัน shoot (ทีม in-house 2 คน + กล้อง 4K)",
      "8 vertical clips (Reels / TikTok / Shorts) ตัดสำเร็จ + แคปชั่น",
      "30 ภาพ product / lifestyle retouched",
      "ส่งไฟล์พร้อมโพสต์ + brief วันโพสต์ที่เหมาะสม",
      "ส่งมอบใน 7-10 วัน",
    ],
    features_en: [
      "1 shoot day (2-person in-house crew + 4K camera)",
      "8 ready-to-post vertical clips (Reels / TikTok / Shorts) + captions",
      "30 retouched product / lifestyle photos",
      "Delivery files + recommended posting brief",
      "Turnaround: 7-10 days",
    ],
    channels: [],
    channels_en: [],
    best_fit:
      "ลูกค้าที่ดูแลเพจเอง แต่ขาดวิดีโอคุณภาพ / brand ที่จะลง campaign / restock content รายไตรมาส",
    best_fit_en:
      "Brands that manage their own page but lack quality video / campaign restock / quarterly content refresh",
    is_recommended: false,
    sort_order: 1,
    is_active: true,
  },
  {
    id: "fallback-p2",
    section: "production",
    name: "CI & BRAND IDENTITY KIT — วางรากแบรนด์",
    name_en: "CI & Brand Identity Kit",
    subtitle: null,
    price: 29900,
    features: [
      "Brand workshop 1 รอบ",
      "Logo system + secondary mark + lockup",
      "Color palette + typography system",
      "Brand guideline PDF เล่มสมบูรณ์",
      "Social media template (FB / IG / TikTok / LINE Rich Menu)",
      "Stationery: นามบัตร / menu / signage template",
      "ส่งมอบเป็น Figma + AI/PSD source",
      "ระยะเวลา 4-5 สัปดาห์",
    ],
    features_en: [
      "1 brand workshop session",
      "Logo system + secondary mark + lockup",
      "Color palette + typography system",
      "Complete brand guideline PDF",
      "Social templates (FB / IG / TikTok / LINE Rich Menu)",
      "Stationery: business card / menu / signage template",
      "Delivered as Figma + AI/PSD source files",
      "Timeline: 4-5 weeks",
    ],
    channels: [],
    channels_en: [],
    best_fit: "ร้านใหม่ / brand rebrand / startup ที่กำลังเข้าตลาด",
    best_fit_en:
      "New shops / brand refreshes / startups entering the market",
    is_recommended: true,
    sort_order: 2,
    is_active: true,
  },
  {
    id: "fallback-p3",
    section: "production",
    name: "BRAND STORY FILM — หนังโฆษณาแบรนด์",
    name_en: "Brand Story Film — Hero Video Production",
    subtitle: null,
    price: 59900,
    features: [
      "Pre-production: concept + script + storyboard",
      "2 วัน shoot (4K + drone + lighting + audio team)",
      "1 hero video 60-90 วินาที + 3 cut-down (15s / 30s / vertical)",
      "20 behind-the-scene photos",
      "Voiceover TH/EN + sound design + color grade",
      "Master file + delivery 3 platforms",
      "ระยะเวลา 3-4 สัปดาห์",
    ],
    features_en: [
      "Pre-production: concept + script + storyboard",
      "2 shoot days (4K + drone + lighting + audio team)",
      "1 hero video 60-90s + 3 cut-downs (15s / 30s / vertical)",
      "20 behind-the-scenes photos",
      "TH/EN voiceover + sound design + color grade",
      "Master file + delivery for 3 platforms",
      "Timeline: 3-4 weeks",
    ],
    channels: [],
    channels_en: [],
    best_fit:
      "Brand launch / property project / hotel grand opening / brand refresh ที่ต้องการ hero film",
    best_fit_en:
      "Brand launches / property projects / hotel grand openings / refreshes that need a hero film",
    is_recommended: false,
    sort_order: 3,
    is_active: true,
  },
];

export const fallbackPortfolio: PortfolioItem[] = [
  { id: "fb-1", title: "Beverage", category: "beverage", image_url: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 1, is_active: true },
  { id: "fb-2", title: "Food", category: "food", image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 2, is_active: true },
  { id: "fb-3", title: "Graphic Ad", category: "graphic", image_url: "https://images.unsplash.com/photo-1621505963574-8b6eb063b5db?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 3, is_active: true },
  { id: "fb-4", title: "Product", category: "product", image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 4, is_active: true },
  { id: "fb-5", title: "Beverage 2", category: "beverage", image_url: "https://images.unsplash.com/photo-1536935338788-846bb9981813?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 5, is_active: true },
  { id: "fb-6", title: "Graphic Ad Main", category: "graphic", image_url: "https://images.unsplash.com/photo-1559132578-838eb04fb870?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 6, is_active: true },
  { id: "fb-7", title: "Japanese Food", category: "food", image_url: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 7, is_active: true },
  { id: "fb-8", title: "Beverage 3", category: "beverage", image_url: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 8, is_active: true },
  { id: "fb-9", title: "Bakery Product", category: "product", image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 9, is_active: true },
  { id: "fb-10", title: "Graphic Promo", category: "graphic", image_url: "https://images.unsplash.com/photo-1588612140660-f138804918ec?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 10, is_active: true },
  { id: "fb-11", title: "Food Delivery", category: "food", image_url: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 11, is_active: true },
  { id: "fb-12", title: "Coffee", category: "beverage", image_url: "https://images.unsplash.com/photo-1544145945-f90425340c7e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80", sort_order: 12, is_active: true },
];

export const fallbackReels: Reel[] = [
  { id: "fr-1", caption: "วิดีโอรีวิวสินค้าสไตล์ Tiktok ดึงดูดสายตา #production #review", audio_text: "Original Audio - De Duck Agency Production Team", image_url: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 12500, likes: 3400, shares: 128, video_url: null, sort_order: 1, is_active: true },
  { id: "fr-2", caption: "พรีเซนต์เมนูอาหาร ให้น่าทานมากยิ่งขึ้น #Foody", audio_text: "Trending Audio - Food Vibe", image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 8900, likes: 2100, shares: 85, video_url: null, sort_order: 2, is_active: true },
  { id: "fr-3", caption: "เก็บภาพบรรยากาศงาน Corporate ให้ดูพรีเมียม #Event", audio_text: "Corporate Background Music", image_url: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 15000, likes: 4200, shares: 310, video_url: null, sort_order: 3, is_active: true },
  { id: "fr-4", caption: "เบื้องหลังการทำงานทีมโปรดักชั่น #BTS", audio_text: "Original Audio - De Duck Agency Production Team", image_url: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 9200, likes: 1800, shares: 45, video_url: null, sort_order: 4, is_active: true },
  { id: "fr-5", caption: "เทคนิคการถ่ายภาพสินค้าให้ปัง #Photography", audio_text: "Viral Beat - Top Trend", image_url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 11300, likes: 2500, shares: 150, video_url: null, sort_order: 5, is_active: true },
  { id: "fr-6", caption: "แฟชั่นวิดีโอ โปรโมทเสื้อผ้าแบรนด์ดัง #FashionShoot", audio_text: "Pop Style - Make it shine", image_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 32100, likes: 8900, shares: 620, video_url: null, sort_order: 6, is_active: true },
  { id: "fr-7", caption: "มุมคาเฟ่ชิลๆ Vibe ดีม๊ากกก #CafeHopping", audio_text: "Chill Lofi Beats - Morning Coffee", image_url: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 7500, likes: 1100, shares: 32, video_url: null, sort_order: 7, is_active: true },
  { id: "fr-8", caption: "เซ็ตอัพไฟสตูดิโอแบบโปร จัดแสงให้สวยกริบ #Studio", audio_text: "Original Audio - De Duck Agency Production Team", image_url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 14200, likes: 3600, shares: 215, video_url: null, sort_order: 8, is_active: true },
  { id: "fr-9", caption: "มุมมองใหม่ด้วยโดรน สุดอลังการ #DroneView", audio_text: "Epic Cinematic Drone Sound", image_url: "https://images.unsplash.com/photo-1508672019048-805c876b67e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 18500, likes: 5600, shares: 480, video_url: null, sort_order: 9, is_active: true },
  { id: "fr-10", caption: "พอดแคสต์สัมภาษณ์สุด Exclusive ภาพคมเสียงชัด #Podcast", audio_text: "Original Audio - De Duck Agency Production Team", image_url: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80", views: 24800, likes: 6200, shares: 890, video_url: null, sort_order: 10, is_active: true },
];
